version: '3.8'

services:
  backend:
    build: ./backend
    image: varshneysarthak/safeconvert-backend:latest
    ports:
      - "8888:8000"
    volumes:
      - temp_data:/app/temp
    environment:
      - UPLOAD_DIR=/app/temp

  frontend:
    build: ./frontend
    image: varshneysarthak/safeconvert-frontend:latest
    ports:
      - "3333:3000"

    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8888

volumes:
  temp_data:
